services:
  - type: web
    name: olympics-api
    runtime: docker
    dockerfilePath: ./olympics_api/Dockerfile
    dockerContext: ./olympics_api
    plan: free
    healthCheckPath: /
    envVars:
      - key: ENV
        value: prod
